### ISSUE TITLE
[BUG] in 3.03 --keepinfo option fails to keep pdfinfo (title, subject, keywords, author)

### ISSUE THREAD

**Issue by lemniscati** [rrthomas/pdfjam#25]
# The option  `--keepinfo` fails to keep pdfinfo (title, subject, keywords, author)

Rewritten  to clarify the points :)

## Expected

- pdfinfo  (title, subject, keywords, author) should be kept.

## Problems

- Title will be lost.
- Subject, Keywords, and Author will get extra strings.
- Some symbols like `き[#$%^&_{}~]` will be lost or broken.

## How to reproduce

1. Prepare `pdfjam` at 9664dd92ea9385f9e60a397561ec238305fcea92 and [`sample.pdf`](https://github.com/rrthomas/pdfjam/files/4642995/sample.pdf)
2. Running
   ````
   pdfjam --keepinfo sample.pdf
   ````
   produces [`sample-pdfjam.pdf`](https://github.com/rrthomas/pdfjam/files/4642988/sample-pdfjam.pdf).
   Note that an error `pdfjam: sed s/^Title:\\\s\*//: not found` occurs.
3. Checking these PDFs by pdfinfo results in:
   ````
   $ pdfinfo sample.pdf
   Title:          X1き[#$%^&_{}~] Sample Title [#$%^&_{}~]1X
   Subject:        X2え[#$%^&_{}~] Test Subject [#$%^&_{}~]2X
   Keywords:       X3る[#$%^&_{}~] Smugged Keywords [#$%^&_{}~]3X
   Author:         X4よ[#$%^&_{}~] Kitchen Author [#$%^&_{}~]4X
   Creator:        Alternative Creator
   Producer:       dvipdfmx (20170318)
   CreationDate:   Mon May 18 17:26:09 2020 JST
   Tagged:         no
   UserProperties: no
   Suspects:       no
   Form:           none
   JavaScript:     no
   Pages:          1
   Encrypted:      no
   Page size:      419.53 x 595.28 pts
   Page rot:       0
   File size:      4009 bytes
   Optimized:      no
   PDF version:    1.5
   
   $ pdfinfo sample-pdfjam.pdf
   Title:
   Subject:        Subject: X2[&&&&&&&&&] Test Subject [&&&&&&&&&]2X
   Keywords:       Keywords: X3[&&&&&&&&&] Smugged Keywords [&&&&&&&&&]3X
   Author:         Author: X4[&&&&&&&&&] Kitchen Author [&&&&&&&&&]4X
   Creator:        LaTeX with hyperref package
   Producer:       pdfTeX-1.40.18
   CreationDate:   Mon May 18 17:26:18 2020 JST
   ModDate:        Mon May 18 17:26:18 2020 JST
   Tagged:         no
   UserProperties: no
   Suspects:       no
   Form:           none
   JavaScript:     no
   Pages:          1
   Encrypted:      no
   Page size:      595.276 x 841.89 pts (A4)
   Page rot:       0
   File size:      28088 bytes
   Optimized:      no
   PDF version:    1.5
   
   $
   ````

**Comment by lemniscati** [comment]
The test above was done on Ubuntu 18.04 LTS.

This bug will be fixed by PR #23 (which is closed), but I think PR #24 is better.

**Comment by lemniscati** [comment]
Another example which `pdfjam` (9664dd92ea9385f9e60a397561ec238305fcea92) fails to process:
````
pdfjam --pdftitle '\' sample.pdf
````

And it says on Ubuntu 18.04 LTS:
````
...
  pdfjam: FAILED.
          The call to /usr/bin/pdflatex resulted in an error.
...
````

This bug won't be fixed by PR #23 (which is closed), but it will be fixed by PR #24.

**Comment by DavidFirth** [comment]
Many thanks @lemniscati for this.  I will review it as soon as I can (which might not be for a while, due to other commitments).

**Comment by sebma** [comment]
@DavidFirth 
I believe the PR #33 fixes the pb.
Hope it will be merge soon.

**Comment by lemniscati** [comment]
@sebma 
Does PR #33 makes it work?
```
pdfjam --pdftitle '\' sample.pdf
```
I think it brings an error, still.

**Comment by sebma** [comment]
@lemniscati I was talking about the `pdfjam: sed s/^Title:\\\s\*//: not found.` issue (which you reported in the first place) which can be fixed by the PR #33.

You're theoretical example should be reported in another issue :
It has nothing to do with `--pdftitle` because this other example can produce the same error :
```pdfjam --pdfauthor '\' sample.pdf```

BTW : Why would you need to initialize PDF information with a backslash, anyway ?

**Comment by lemniscati** [comment]
Thank you @sebma for your patch.
Sorry for my ambiguous description of this issue.

The point is:

# The option  `--keepinfo` fails to keep pdfinfo (title, subject, keywords, author)

## Expected

- pdfinfo  (title, subject, keywords, author) should be kept.

## Problems

- Title will be lost.
- Subject, Keywords, and Author will get extra strings.
- Some symbols like `き[#$%^&_{}~]` will be lost or broken.

## How to reproduce

1. Prepare `pdfjam` at 9664dd92ea9385f9e60a397561ec238305fcea92 and [`sample.pdf`](https://github.com/rrthomas/pdfjam/files/4642995/sample.pdf)
2. Running
   ````
   pdfjam --keepinfo sample.pdf
   ````
   produces [`sample-pdfjam.pdf`](https://github.com/rrthomas/pdfjam/files/4642988/sample-pdfjam.pdf).
   Note that an error `pdfjam: sed s/^Title:\\\s\*//: not found` occurs.
3. Checking these PDFs by pdfinfo results in:
   ````
   $ pdfinfo sample.pdf
   Title:          X1き[#$%^&_{}~] Sample Title [#$%^&_{}~]1X
   Subject:        X2え[#$%^&_{}~] Test Subject [#$%^&_{}~]2X
   Keywords:       X3る[#$%^&_{}~] Smugged Keywords [#$%^&_{}~]3X
   Author:         X4よ[#$%^&_{}~] Kitchen Author [#$%^&_{}~]4X
   Creator:        Alternative Creator
   Producer:       dvipdfmx (20170318)
   CreationDate:   Mon May 18 17:26:09 2020 JST
   Tagged:         no
   UserProperties: no
   Suspects:       no
   Form:           none
   JavaScript:     no
   Pages:          1
   Encrypted:      no
   Page size:      419.53 x 595.28 pts
   Page rot:       0
   File size:      4009 bytes
   Optimized:      no
   PDF version:    1.5
   
   $ pdfinfo sample-pdfjam.pdf
   Title:
   Subject:        Subject: X2[&&&&&&&&&] Test Subject [&&&&&&&&&]2X
   Keywords:       Keywords: X3[&&&&&&&&&] Smugged Keywords [&&&&&&&&&]3X
   Author:         Author: X4[&&&&&&&&&] Kitchen Author [&&&&&&&&&]4X
   Creator:        LaTeX with hyperref package
   Producer:       pdfTeX-1.40.18
   CreationDate:   Mon May 18 17:26:18 2020 JST
   ModDate:        Mon May 18 17:26:18 2020 JST
   Tagged:         no
   UserProperties: no
   Suspects:       no
   Form:           none
   JavaScript:     no
   Pages:          1
   Encrypted:      no
   Page size:      595.276 x 841.89 pts (A4)
   Page rot:       0
   File size:      28088 bytes
   Optimized:      no
   PDF version:    1.5
   
   $
   ````

**Comment by lemniscati** [comment]
I guess that PR #33 is included by PR #23 , and that PR #24 would be better than #23 (cf. https://github.com/rrthomas/pdfjam/issues/25#issuecomment-630043996).

**Comment by sebma** [comment]
@lemniscati Why not fix one pb. at a time ?
First, the sed quoting pb. according to issue #35 with a merge with PR #33 
And then merge PR #24, is that ok ?

**Comment by lemniscati** [comment]
@sebma I have no reason to refuse dividing these problems and changes. Thank you.
My description of this issue was bad, so I've rewritten it.

**Comment by sebma** [comment]
@lemniscati Cool :smile: Thanks :+1:

**Comment by lemniscati** [comment]
#24 fixes the issue.

**Comment by JohnRobson** [comment]
"--keepinfo" stop working

**Comment by lemniscati** [comment]
@JohnRobson
Please, try [the latest version](https://github.com/rrthomas/pdfjam/blob/3019b189d63ec8e93f5d16bbb45b4d472417d87a/bin/pdfjam).
And describe the situation and how to reproduce it.
