### ISSUE TITLE
TeX Live and dependencies

### ISSUE THREAD

**Issue by DavidFirth** [rrthomas/pdfjam#31]
_Matthias_ has kindly alerted me to the fact that it is possible to install pdfjam via TeX Live but to then have some dependencies missing from your installation.  (The example given by Matthias was that `pdflscape.sty` was missing from his installation and that caused an error when running `pdfjam`.)

I do not know enough about TeX Live to be able to solve this (and regrettably I have no time to find out).  Matthias kindly pointed me to information at [https://tug.org/texlive/pkgcontrib.html#deps](https://tug.org/texlive/pkgcontrib.html#deps), but it seems (from that information) that CTAN's administrators "do not particularly recommend" doing what is described there.

If somebody else knows how to fix this (including tracking reliably all of the dependencies!) then of course that would be good.  I suppose that a simple solution could be just to remove pdfjam from TeX Live?

**Comment by GuillaumeFromage** [comment]
There are examples of how to check for dependencies in similar forks of this project, such as:
https://github.com/jenom/pdfbook2/blob/master/pdfbook2/pdfbook2#L144

**Comment by rrthomas** [comment]
Thanks for the tip, @GuillaumeFromage; I would welcome a PR that implements this.

**Comment by rrthomas** [comment]
I don't know the list TBH, so I'd be quite happy with your second suggestion: implement the example mentioned and wait for issues. I consider pdfjam to be in maintenance mode, so I don't think wholesale improvements that have no immediate pay-off are worth the effort.

**Comment by mgkurtz** [comment]
After replacing `everyshi` with the hooks introduced into LaTeX in 2020, the only dependency is `pdfpages` and we print a sensible error message, if this is missing.
