### ISSUE TITLE
pdfjam needs a new maintainer

### ISSUE THREAD

**Issue by DavidFirth** [rrthomas/pdfjam#32]
The pdfjam project is now orphaned.

The issue is that I am not a professional programmer, and I have neither the skill nor the time to maintain the pdfjam script (and its associated documentation) any longer.

I apologise here to those who have contributed issues and/or pull requests that are unresolved, still.  I am truly grateful for those contributions.  But I simply cannot continue to be the person responsible for fixing/reviewing/merging or whatever it takes to fix things and republish (e.g., to TeX Live).

Some of the issues reported relate to portability between operating systems.  Others are suggestions or requests for new features.  I find it hard to judge which of these things are important (because pdfjam works fine for me, on my system and for the things I want it to do!).  And my experience is that adding capabilities requested by one user will typically break something (unexpectedly, to me) for another user --- which must surely count as evidence of my lack of skill in programming!

The frequency of issue reports is not high (around 30 in the last year I think).  The project is GPL.  I hope it continues to be useful.  If someone else wants to maintain it (and even develop it?) I would be pleased about that.  For now, though, the pdfjam package (here on GitHub, and also in TeX Live) has no maintainer.

**Comment by DavidFirth** [comment]
I am still, for now, listed at CTAN as the (inactive) maintainer of pdfjam.  I hope this might change at some point, if someone else wants to take the software forward.

**Comment by rrthomas** [comment]
I would be happy to take over. I just filed an issue, so I have an immediate interest. I would not plan to add much in the way of features, but would be happy to assess and apply patches and fix bugs.

I'm the maintainer of `psutils`; indeed, it's partly because I would like to be able to work with PDF files directly that I'm inclined to put some effort into pdfjam. At the moment I find myself still using `pdf2ps | psutils | ps2pdf` because of weirdness like the bug I just reported in pdfjam; it would be nice to solve that!

**Comment by DavidFirth** [comment]
Many thanks @rrthomas for this.  I will happily hand over pdfjam to you.

I don't know how best to arrange this, for a smooth handover.  If you would prefer to settle the details offline, please feel free to write to my Warwick email address for that --- find it via [https://warwick.ac.uk/dfirth](https://warwick.ac.uk/dfirth).

**Comment by DavidFirth** [comment]
@rrthomas many thanks again for taking this on, it is much appreciated.

The CTAN package (which feeds TeXLive) still lists me as the (inactive) maintainer.  Do you @rrthomas want to become the maintainer of that as well, or do you prefer to leave that as an open issue to be resolved still?  I hope it's clear what I mean.  [https://www.ctan.org/tex-archive/support/pdfjam](https://www.ctan.org/tex-archive/support/pdfjam)

**Comment by rrthomas** [comment]
Feel free to let CTAN support know I maintain it!

**Comment by DavidFirth** [comment]
Thanks --- the CTAN record has now been changed.  I am very happy to be able to close this issue now.
