### ISSUE TITLE
pdfjam seems to change the margins when printing A5 pages to A4 as booklet

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/pdfjam#37]
If I run:

```
pdfjam --landscape --suffix book foo.pdf --booklet true --paper a4
```

where `foo.pdf` is A5, then the A5 pages are not simply impressed on the A4 sheet; the margins are changed. See jenom/pdfbook2#10

**Comment by DavidFirth** [comment]
My usual approach to diagnosing a problem like this is to run again with `--no-tidy`, and then get the resulting `.tex` file, to check that against the documentation of the _pdfpages_ package.

**Comment by rrthomas** [comment]
Thanks for the hint! So in my case, `a.tex` is:

```
\batchmode
\documentclass[a4,landscape]{article}
\usepackage[utf8]{inputenc}
\usepackage{pdfpages}

\begin{document}
\includepdfmerge[booklet=true]{/tmp/pdfjam-tZUmNi/source-1.pdf,-}
\end{document}
```

No mention that I can find of any margins. I tried adding the `noautoscale=true` option to `\includepdfmerge`, which changed the margins but without fixing them. Removing `booklet=true` and changing to `a4,landscape` to `a5paper` restores the correct margins (the process is now logically a no-op). Adding back `a4,landscape` and adding the option `nup=2x1` to `\includepdfmerge` makes the margins go wrong again, suggesting the problem is with the `nup` option: both `delta` and `offset` default to zero, and centring A5 pages on A4 2up should obviously not change them.

I've written to Andreas Matthias with a bug report for pdfpages.

**Comment by rrthomas** [comment]
I found the bug (it is, in fact, in pdfjam):

```
LaTeX Warning: Unused global option(s):
    [a4].
```

That should be `a4paper`.

**Comment by rrthomas** [comment]
For example, by treating warnings as errors? Would this be a reasonable thing to do with pdfjam?

https://stackoverflow.com/questions/3244908/how-do-i-treat-latex-warnings-as-errors

**Comment by rrthomas** [comment]
There's one remaining problem I realize I haven't gotten to the bottom of: I shouldn't've needed to specify the paper size in the first place, as pdfjam should have the right default. When I execute `pdfjam --help` it says:

```
                  [Default for you at this site: paper=]
```

So either TeXLive, or Ubuntu's packaging of it, have not wired it up with appropriate defaults? (Looking at the rest of the `--help` output, no default is set.

**Comment by DavidFirth** [comment]
> I found the bug:
> 
> ```
> LaTeX Warning: Unused global option(s):
>     [a4].
> ```
> 
> That should be `a4paper`. In this case it's my error (because I typed `--paper a4`), though it would be nice if pdfjam gave a warning at least.

I agree, that would be nice.

**Comment by DavidFirth** [comment]
> For example, by treating warnings as errors? Would this be a reasonable thing to do with pdfjam?
> 
> https://stackoverflow.com/questions/3244908/how-do-i-treat-latex-warnings-as-errors

Well, LaTeX does tend to give a *lot* of warnings.  So this might not be a great idea I suspect.

Worth noting that the values allowed for `--paper` are all the ones allowed by LtTeX, *plus* all the ones allowed by the `geometry` package.  That's a potentially moving target.  So constructing a reliable test for a valid `--paper` setting might not be so easy.  (I guess that's why I didn't do it from the start.)

**Comment by rrthomas** [comment]
Yes, I thought about that: in general it gives a lot of warnings, but I'm not sure that it should for a document constructed by pdfjam. Maybe worth a try…

**Comment by DavidFirth** [comment]
> There's one remaining problem I realize I haven't gotten to the bottom of: I shouldn't've needed to specify the paper size in the first place, as pdfjam should have the right default. When I execute `pdfjam --help` it says:
> 
> ```
>                   [Default for you at this site: paper=]
> ```
> 
> So either TeXLive, or Ubuntu's packaging of it, have not wired it up with appropriate defaults? (Looking at the rest of the `--help` output, no default is set.

Oh, this is indeed unfortunate, and not intended.  I can confirm that the same holds on my fresh install of TeXLive in Fedora 33.

The relevant part of the README at [https://github.com/rrthomas/pdfjam#config](https://github.com/rrthomas/pdfjam#config) tells someone how to configure their installation of pdfjam.  But of course TeXLive does not actually *do* any of that; instead it just keeps a copy of the `pdfjam.conf` template in the pdfjam directory inside the TeXLive installation.  I don't know what would be a good way around this, ie something that robustly helps users who have installed pdfjam via TeXLive.

**Comment by mgkurtz** [comment]
The default paper setting is done now. To bring warnings to peoples attention, I opened issue #88.
