### ISSUE TITLE
where did the pdfjam-extras page go?

### ISSUE THREAD

**Issue by ricopicone** [rrthomas/pdfjam#39]
The links on the README are 404ing ...

**Comment by ricopicone** [comment]
It looks like David Firth's account still has it: https://github.com/DavidFirth/pdfjam-extras

**Comment by DavidFirth** [comment]
Yes, that still sits in my github account.  Still unmaintained.  I'm happy either for it to stay there, or for it to be transferred to @rrthomas, or for someone else to maintain it if they want.

**Comment by rrthomas** [comment]
Very happy to take this over too.

**Comment by DavidFirth** [comment]
Thanks @rrthomas for this.  Transfer of pdfjam-extras to you has now been requested.

**Comment by rrthomas** [comment]
Accepted, thanks!
