### ISSUE TITLE
There is no option to select the reading language!

### ISSUE THREAD

**Issue by alial3mamy** [rrthomas/pdfjam#41]
Like Arabic, Chinese, and others, it reads from right to left, not like in English, so I ask you to please add an option to specify the direction of reading.

**Comment by rrthomas** [comment]
Sorry, I don't quite understand. Are you talking about the order in which pages are imposed on the new pages by the `-nup` option?

**Comment by alial3mamy** [comment]
When reading an English book, you turn the page to the left, but in Arabic, for example, you turn the paper to the right. This is the direction of reading. Meaning that the last paper is in English, reading the Arabs is the first paper. Thank you for understanding and accepting suggestions, I hope you find a way to do so quickly ^^ I loved your program.

**Comment by alial3mamy** [comment]
If my words are not clear, tell me how to print the pages in a specific order, for example: 4,1,3,2. Because man pages is not clear.

**Comment by DavidFirth** [comment]
For selecting pages (in any order), please see `pdfjam --help` and/or the README (specifically Example 2 therein) at https://github.com/rrthomas/pdfjam
