### ISSUE TITLE
Is there a way to add the page numbers?

### ISSUE THREAD

**Issue by tlamadon** [rrthomas/pdfjam#42]
I found the following help:
https://linux.die.net/man/1/pdfjam-slides3up#:~:text=To%20put%20page%20numbers%20on,can%20be%20used%20by%20LateX.

but I can seem to find the option in pdf-jam itself?

thank you!

**Comment by DavidFirth** [comment]
If you look at pdfjam-slides3up (ie, look at the script in a terminal or a text editor) you will see how it's done there.

Something like `pdfjam --pagecommand '{\thispagestyle{plain}}'` ought to work?

**Comment by tlamadon** [comment]
it did work! Thank you!
