### ISSUE TITLE
The --delta option is not mentionded in the output of "pdfjam --help"

### ISSUE THREAD

**Issue by ale03068** [rrthomas/pdfjam#43]
I find the existence of this option with google. Should all option be listed in the in the "--help" or in the manual?

**Comment by DavidFirth** [comment]
For what it's worth: my opinion is that the documentation for `pdfjam` should not try to reproduce the documentation for the `pdfpages` package.  The design of `pdfjam` as it stands is that it is (only) a convenient front-end script for features of `pdfpages`.  The developer of `pdfpages` documents that package's features authoritatively.  And `pdfjam` does not need to know when those features change, or when new features are added, for example.

The relevant part of the `pdfjam --help` output is this:
`    --KEY VALUE
                  Specify options to '\includepdfmerge', in the LaTeX
                  'pdfpages' package.  Here KEY is the name of any of the
                  many options for '\includepdfmerge', and VALUE is a
                  corresponding value.  Examples are
                      --nup 2x1     (for 2-up side-by-side imposition)
                      --scale 0.7   (to scale all input pages to 70% size)
                      --offset '1cm 0.5cm'
                                    (to offset all pages -- note the quotes!)
                      --frame true  (to put a frame round each input page)
                      --trim '1cm 2cm 1cm 2cm' --clip true
                                    (to trim those amounts from left, bottom,
                                     right and top, respectively, of input 
                                     pages) 
                  etc., etc.  For more information see the manual for
                  the 'pdfpages' package, at
                  http://www.ctan.org/tex-archive/macros/latex/contrib/pdfpages`
I haven't checked today, but I believe that the `--delta` option is still covered by this.

**Comment by ale03068** [comment]
Yes, you are right in http://www.ctan.org/tex-archive/macros/latex/contrib/pdfpages the is the explanation of "delta".
But they not specify the syntax use in pdfjam, yes you can do a guess based on the examples listed in the --help but it is not the most straight forward in my opinion. 
In my case I didn't realize reading fast the --help the concept "here some examples, go to the pdfpages for the complete list".
Thanks for the answer.

**Comment by rrthomas** [comment]
I have improved `--help` to refer to the `pdfpages` docs; I refer to #30 for the other way in which I propose to improve the pdfjam docs.
