### ISSUE TITLE
Error on pdfjam: "tty is connected to connected to stdin, no PDF/JPG/PNG file found"

### ISSUE THREAD

**Issue by raspatan** [rrthomas/pdfjam#46]
I'm trying to rotate a PDF using the command

`pdfjam --landscape --angle==270 test.pdf`

but I get the following:
```

  pdfjam: This is pdfjam version 3.03.
  pdfjam: Reading any site-wide or user-specific defaults...
          (none found)
  pdfjam: No PDF/JPG/PNG source specified: input is from stdin.
  pdfjam: Effective call for this run of pdfjam:
          /usr/bin/pdfjam --landscape --angle==270 'test.pdf' -- /dev/stdin - 
  pdfjam ERROR: tty is connected to connected to stdin, no PDF/JPG/PNG file found
```
Problem occurs even if file `test.pdf` does not exist in folder. 

I cannot find a similar problem online. I'm running Ubuntu 20.04. Any ideas?

PD: is there a typo in the error message? (repeated "connected to")

**Comment by DavidFirth** [comment]
I think that the call should have been
```
pdfjam --landscape --angle 270 test.pdf
```
(i.e., without the "==")  

Hopefully that will work for you @raspatan .

The error message with repetition does look like something to fix, though!

**Comment by raspatan** [comment]
@DavidFirth Correct! Problem was the double ==. Thanks!
