### ISSUE TITLE
Two shellcheck issues

### ISSUE THREAD

**Issue by habere-et-dispertire** [rrthomas/pdfjam#49]
Shellcheck -- @koalaman -- reports two types of issues with `pdfjam`:

- [Multiple redirections compete for stdout.](https://www.shellcheck.net/wiki/SC2261) Use cat, tee, or pass filenames instead.
- [This backslash+linefeed is literal.](https://www.shellcheck.net/wiki/SC1004) Break outside single quotes if you just want to break the line.

Running `shellcheck /Library/TeX/texbin/pdfjam` provides the full context:

> /Library/TeX/texbin/pdfjam:306:47: error: Multiple redirections compete for stdout. Use cat, tee, or pass filenames instead. [SC2261]
> /Library/TeX/texbin/pdfjam:306:58: error: Multiple redirections compete for stdout. Use cat, tee, or pass filenames instead. [SC2261]
> /Library/TeX/texbin/pdfjam:313:47: error: Multiple redirections compete for stdout. Use cat, tee, or pass filenames instead. [SC2261]
> /Library/TeX/texbin/pdfjam:313:58: error: Multiple redirections compete for stdout. Use cat, tee, or pass filenames instead. [SC2261]
> /Library/TeX/texbin/pdfjam:960:24: note: This backslash+linefeed is literal. Break outside single quotes if you just want to break the line. [SC1004]
> /Library/TeX/texbin/pdfjam:963:24: note: This backslash+linefeed is literal. Break outside single quotes if you just want to break the line. [SC1004]

**Comment by mgkurtz** [comment]
Whatever those issues were about, `shellcheck` now runs successfully and is included in GitHub actions.
