### ISSUE TITLE
Is it possible to add an option to combine pdfs of different sizes?

### ISSUE THREAD

**Issue by developedsoftware** [rrthomas/pdfjam#50]
I have 3 pages - all 250mm high. But the middle page is a spine - 10mm. The left and right pages are 300mm wide. 

At the moment, pdfjam takes the 1st page, and makes every other logical page the same size. So my spine has a massive gap to the right. 

Is there an option to simple combine the pdfs as they are found? I have messed around with the delta option but this applies the same delta to every page.

**Comment by DavidFirth** [comment]
The current behaviour is that all output pages are the same size.  Versions 2.08 and earlier of pdfjam were more limited in lots of respects, but they did (if I remember correctly) allow the mixing of page sizes that you want.  See https://rrthomas.github.io/pdfjam/ for those earlier versions.

**Comment by developedsoftware** [comment]
Thanks for coming back to me David. 

I have 2.08 installed. Is there a CHANGELOG for these old versions anywhere so I can try to revert back to the one that I think will work? I am sure it did work at some point (was scratching my head when I discovered logical pages all get inserted at the same size).

**Comment by DavidFirth** [comment]
I misremembered, sorry: the design change actually came at version 2.00.  See the version history at https://github.com/rrthomas/pdfjam#history --- I suggest to try the last of the 1.* versions, for what you want to achieve.

**Comment by developedsoftware** [comment]
I have tried 1.2.1 and 1.2, both behave exactly as 2.08. 

I am going to try to edit pdfjam to see if I can get it to do what I need. I am certain texlive can do it.

**Comment by DavidFirth** [comment]
@developedsoftware --- sorry, I don't understand.  I suggest to try version 1.21 of the pdfjam package, where you will find a script named `pdfjoin`.  That has very different behaviour from the `pdfjam` script that appears in later versions of the package (2.00 onwards).  And possibly it will do what you want.

Note that there is no `pdfjam` script in package versions prior to 2.00.

There is no pdfjam package version 1.2.1, nor version 1.2.  Possibly you meant to say 1.21 or 1.20 --- but did you actually use either of those?  The behaviour of the scripts therein is very different from the current `pdfjam` script.

**Comment by developedsoftware** [comment]
Yes I noticed that pdf jam wasn’t in that script.

So I used pdf join to merge my 3 different pages together (making a single pdf with 3 different page sizes).

I then tried to use pdfnup to composite these side by side. 

And the result, out of the box, was identical to version 2.0.8

I did notice in 1.2.1 you use includepdfmerge which I think assumes all pages are of equal size…which maybe where the issue lies.

Have 3 pages. Left and right pages are 210mm wide. Middle is 6mm wide (a spine). I just want to stitch them left to right without any padding inbetween or the logical pages being created at the same width…

**Comment by DavidFirth** [comment]
But that still is not correct!  There is no package version 1.2.1.  If you meant to say 1.21, then what you wrote about \includepdfmerge is incorrect: `pdfjoin` version 1.21 used \includepdf, as far as I can see (I just checked that again here).

I suggest to try to make sure you are using `pdfjoin` version 1.21 (the version number is printed at the top of the script's output) and then try to follow the instructions given in `pdfjoin --help`.  I hope that helps you.

**Comment by developedsoftware** [comment]
Apologies, of course I mean 1.21

But I behaved the same as 2.08 (even though I had to issue 2 commands instead of 1).

I will do some more digging.

I think the crux of the issue is that “logical pages are inserted at the same size”. And I think that’s a latex issue - not pdf jam. 

You understand what I am trying to achieve ? My spine is inserted woth the same width as the first logical page in the document

**Comment by DavidFirth** [comment]
I don't really understand still, sorry.  The bahaviour of `pdfjam` in 2.08 and `pdfjoin` in 1.21 are completely different.  And you want the latter, I believe.

**Comment by developedsoftware** [comment]
I will output some files using 1.21 tomorrow and show you my findings. When I ran tests today my spine was inserted at the same width of the first logical page found in the list of input files.

**Comment by DavidFirth** [comment]
Possibly the most helpful thing to do would be to run `pdfjoin --help` (in package version 1.21).  When you do that, do you get the same as I do (i.e., as shown below)?  If so, then I think you can probably achieve what you want if you use the `--fitpaper` and `--noautoscale` arguments appropriately.
`$ ./pdfjoin --help
This is pdfjoin version 1.21
Reading user defaults from ~/.pdfnup.conf

Usage: pdfjoin args
where args must include source pdf filenames and optionally also
* a LaTeX papersize, for example --paper a4paper
                                 --paper letterpaper
* the output page orientation, one of --orient landscape
                                      --orient portrait
* one of --fitpaper true
         --fitpaper false
  to specify whether output page sizes and orientations should match
  those of the input pages.  Use of --fitpaper true overrides --orient.
* a page-trimming specification such as
         --trim "1cm 1cm 1cm 1cm"
  (Note that trimming does not mix well with --frame true.)
* an "offset" specification such as
         --offset "1cm 0.5cm"
  to offset the position of output pages (see the pdfpages manual)
* one of --turn true
         --turn false
  according to whether or not landscape pages should be displayed in
  landscape orientation
* one of --noautoscale true
         --noautoscale false
  for scaling of logical pages to fit (or not)
* a specific name for the output file, e.g. --outfile mybigfile.pdf
* one of --tidy true
         --tidy false
  according to whether or not temporary files should be deleted immediately.
  If --tidy false is used, such files are left in /var/tmp.

Default arguments for you at this site are
   --paper a4paper --trim "0 0 0 0" --offset "0 0" --turn true --noautoscale false --tidy true
   
For information and version history see http://www.warwick.ac.uk/go/pdfjam`

**Comment by developedsoftware** [comment]
Output of pdfjoin --help

Yes looks to be the same. I will do some more digging tomorrow. 

`This is pdfjoin version 1.21

Usage: pdfjoin args
where args must include source pdf filenames and optionally also
* a LaTeX papersize, for example --paper a4paper
                                 --paper letterpaper
* the output page orientation, one of --orient landscape
                                      --orient portrait
* one of --fitpaper true
         --fitpaper false
  to specify whether output page sizes and orientations should match
  those of the input pages.  Use of --fitpaper true overrides --orient.
* a page-trimming specification such as
         --trim "1cm 1cm 1cm 1cm"
  (Note that trimming does not mix well with --frame true.)
* an "offset" specification such as
         --offset "1cm 0.5cm"
  to offset the position of output pages (see the pdfpages manual)
* one of --turn true
         --turn false
  according to whether or not landscape pages should be displayed in
  landscape orientation
* one of --noautoscale true
         --noautoscale false
  for scaling of logical pages to fit (or not)
* a specific name for the output file, e.g. --outfile mybigfile.pdf
* one of --tidy true
         --tidy false
  according to whether or not temporary files should be deleted immediately.
  If --tidy false is used, such files are left in /var/tmp.

Default arguments for you at this site are
   --paper a4paper --trim "0 0 0 0" --offset "0 0" --turn true --noautoscale false --tidy true
   
For information and version history see http://www.warwick.ac.uk/go/pdfjam`

**Comment by developedsoftware** [comment]
As suggested, using a mix of fitpaper and noautoscale in pdf join worked absolutely fine. I can see the PDFs being generated correctly. I can attach these ?

the issue comes when I then take that 3 page document - consisting of 3 pages - middle being a small spine - and running it through pdfnup.

pdfnup inserts the spine at the same width as the first logical page. And then the 3rd page is pushed right off the end. This behavior is exactly the same as 2.0.8. I can attach this also ? Is there anything I can try in pdfnup 1.21 to get it to just stitch from left to right ?

**Comment by DavidFirth** [comment]
Ah right, sorry, I didn't get from your original question that you wanted to put your 3 pages info a single page.  (I had read "combine the pfs" in a different way, meaning to put the separate PDF files into a single 3-page document).  And then I missed your mention of `pdfnup` in what came after, sorry.

What you want to do can be achieved by just using `\includegraphics` in LaTeX, I believe.  You don't need pdfjam for this.

In any case, I think your question does not raise any issue that needs to be fixed in pdfjam.  So maybe this should now be closed?

**Comment by developedsoftware** [comment]
Sorry if I didnt make that clear - yes wanting to "stitch" them left to right. 

So, something similar to the solution provided here ? They mention includegraphics 
https://tex.stackexchange.com/questions/145713/stitch-differently-sized-pages-together

> \documentclass{article}
> \usepackage{geometry}% http://ctan.org/pkg/geometry
> \geometry{margin=0pt,paperwidth=\dimexpr148mm+148mm+1cm,paperheight=210mm}
> \usepackage{atbegshi,graphicx}% http://ctan.org/pkg/{atbegshi,graphicx}
> \setlength{\parindent}{0pt}
> \pagestyle{empty}
> \begin{document}
> \AtBeginShipoutNext{\AtBeginShipoutDiscard}% Remove first page
> \resizebox{148mm}{210mm}{B}% Back
> \resizebox{1cm}{210mm}{S}% Spine
> \resizebox{148mm}{210mm}{F}% Front
> \end{document}

Yes I agree this can be closed. Although I may post my end code in case anybody is wanting to do a similar thing and comes accross this post (if that is OK with you?).

**Comment by developedsoftware** [comment]
I have modified pdfjam 2.08 to output stitched pages left to right even if the pages are of different widths (using the script above essentially). Would you be interested in seeing it to perhaps include in a future release ? 

Includepdfmerge is replaced with resizebox and includegraphics…

perhaps a command line switch could differentiate which implementation to use ?

**Comment by DavidFirth** [comment]
My opinion (only) is that this would be likely to break other functionality of current `pdfjam`.  What you suggest here is certainly outside the scope of the purpose of `pdfjam`, which was (and currently is) to provide a convenient front end to features of the _pdfpages_ package.

**Comment by developedsoftware** [comment]
Fair enough ! Thanks for your help pointing me in the right direction

**Comment by joao8tunes** [comment]
I recently had a similar problem. The difference was that the pages I needed to merge had different dimensions. I tried using `pdfjam`, but I had trouble aligning the pages. I posted a workaround based on LaTeX in the following post: ["How to join multiple PDF pages to a single Page"](https://stackoverflow.com/a/71802078/16109419).

**Comment by bruceleerabbit** [comment]
I didn’t read this whole thread but it seems pdfjam 3.03 has the same problem described by the subject.

My use case:

Someone handles my mail for me while I am away from home. They open the envelope and photograph each page with a smartphone (they don’t have a scanner or the competency to use one). They also photograph the envelope.  The pages are a4 & the envelope is roughly ⅓ of that.  If the `--a4paper` option is used along with:

\includepdfset{fitpaper=true}

there is still a problem because `\includepdfmerge` lacks the ability to re-fit the 2nd page and any page thereafter. So even the envelope appears on an a4 page (which creates the annoyance of scrolling & upscaling). Because the source images are from a camera and not perfectly a4 dimensioned, pdfjam adds whitespace to all pages except the 1st one. Only the first page is properly fit. This fails the principle of least astonishment. Users don’t expect the 1st page to be treated differently than all the other pages.

I’ve discovered that if every doc gets a separate `\includepdf` command, then pages are fit (thus the `fitpaper` option is applied equally to all pages).

I suggest reopening this.

**Comment by mgkurtz** [comment]
@bruceleerabbit: Fitting each page anew would be good indeed. I just tried this with `\includepdf` and it did not even work out there. However, for now, I classified this as an issue with `pdfpages` and thus closed it here.
