### ISSUE TITLE
can pdfjam re-order the pages for simple imposition and n-up print compositing?

### ISSUE THREAD

**Issue by ahillio** [rrthomas/pdfjam#51]
If we're printing a many-page document it's quite possible we need to re-order the pages... the way https://wiki.scribus.net/canvas/Making_a_booklet_with_Scribus_and_Adobe_Reader describes (for the Scribus desktop publishing software of course)...  so for example

A 16-page booklet would print onto 4 sheets of paper:
sheet 1 front: pages 16,1
sheet 1 back: pages 2,15
sheet 2 front: pages 14,3
sheet 2 back: pages 4,13
sheet 3 front: pages 12,5
sheet 3 back: pages 6,11
sheet 4 front: pages 10,7
sheet 4 back: pages 8,9

This booklet form is for laying all the sheets flat on each other and folding them all at once together.

If we want more pages than can be folded this way (as in a book) we might need to fold each sheet individually, which would give us a page order like:
sheet 1 front: pages 4,1
sheet 1 back: pages 2,3
sheet 2 front: pages 8,5
sheet 2 back: pages 6,7
sheet 3 front: pages 12,9
sheet 3 back: pages 10,11
sheet 4 front: pages 16,13
sheet 4 back: pages 14,15
sheet 5 - 200 or more etc would follow this pattern.

Can pdfjam do ordering like this?  (If not, do you happen to know a command line tool which can?)

**Comment by DavidFirth** [comment]
Yes, I believe that all of this is possible with pdfjam.  Note that pdfjam is just a front end for the _pdfpages_ package in LaTeX.  If you haven't looked there already, I recommend the user manual for _pdfpages_ (a link to which should appear if you use `pdfjam --help`) --- all the facilities are documented there.

**Comment by GuillaumeFromage** [comment]
In case anyone falls on this, you can with --booklet=true and its friends (if necessary): --nup=2x1 --landscape --paper ledger, etc.

**Comment by ahillio** [comment]
Yes this is great, thanks. Commands like:
`pdfjam --nup 2x1 --landscape --signature 4 myfile.pdf`
are what I was looking for.
