### ISSUE TITLE
Feature request: allow shortedge rotation of pages from pdfjam

### ISSUE THREAD

**Issue by GuillaumeFromage** [rrthomas/pdfjam#55]
Hi!

There is a pretty good workaround to get pages odd pages 180 degrees when making signatures, by using: pdfjam --preamble '\usepackage{everyshi}\makeatletter\EveryShipout{\ifodd\c@page\pdfpageattr{/Rotate 180}\fi}\makeatother' (don't worry, I'm not smart, I've took this from https://github.com/jenom/pdfbook2/blob/master/pdfbook2/pdfbook2#L153). The issue is that this is a clunky workaround, especially since it rely on everyshi.sty, which I don't know what that is, but I know there should be a check for it in code.

Is this some oddball feature that nobody uses? Should I just go ahead and implement? Are there plans to migrate this code to python?

**Comment by GuillaumeFromage** [comment]
Never mind the python bit, as the python code seems to be ported from shell in pdfjam-extras, so it isn't a hassle to recode.

**Comment by rrthomas** [comment]
I would be happy to receive a PR for this!
