### ISSUE TITLE
I'm so confused with a use but not exist in documentation

### ISSUE THREAD

**Issue by abdulbadii** [rrthomas/pdfjam#58]
I'm so confused with the use of option:
`--noautoscale`

I keep using it as it works great, fit in my need, that since one taught me to use it but.. it's not existing in documentation at all !

`$ pdfjam  --help| grep noautoscale`

Please help clarify on this as clearly as possible

**Comment by rrthomas** [comment]
As it says in `README.md`:

>In addition to the arguments that are explicitly documented there, `pdfjam` provides access to all of the options of the **pdfpages** package: that's a large number of options, and it's a set of options that might change, so users are referred to the current [pdfpages manual (PDF)](http://www.ctan.org/tex-archive/macros/latex/contrib/pdfpages/pdfpages.pdf) to see what's available.

And as it says in `pdfjam --help`:

```
'options' are pdfpages specifications in the form '--KEY VALUE' (see below)
…
 --KEY VALUE
                  Specify options to '\includepdfmerge', in the LaTeX
                  'pdfpages' package…
```
