### ISSUE TITLE
Option to respect original paper size (for eg. beamer)

### ISSUE THREAD

**Issue by ysalmon** [rrthomas/pdfjam#59]
Hello,

I have to extract the beginning of a PDF created with beamer, which has a non-standard "paper" size.

It does not seem easy to do with ``pdfjam`` : it seems I would need to check what that format is and specify it manually.

Is there a better way ?

**Comment by DavidFirth** [comment]
Have you tried the option `--fitpaper true` ?  It works for me, here.  (as documented in the pdfpages manual)

**Comment by ysalmon** [comment]
I did not, but I should have ! Thank you.

**Comment by bruceleerabbit** [comment]
This is somewhat related to bug #50.  `--fitpaper true` would work as long as all pages are the same dimension. But if there is variation in the page dimensions then you’ll probably run into problems.  ATM I use `--no-tidy` & edit the latex doc to replace `\includepdfmerge` with a separate `\includepdf` for each doc.
