### ISSUE TITLE
Can't align content vertically top instead of vertically center of the page

### ISSUE THREAD

**Issue by ahmedmohiduet** [rrthomas/pdfjam#60]
While running: 
`pdfjam --outfile output.pdf --paper a4paper --landscape input.pdf `

This generates output pdf where I have content at the center (vertically+horizontally) of the page. However I'm looking to have the content center only horizontally, but keep them vertically at the top.

Can't find any configuration options at `--help` documentation. Can it be done?

**Comment by DavidFirth** [comment]
The main options are documented in the pdfpages manual (as is mentioned in `pdfjam --help`).

If your input pages are all the same height, then something like `--offset "0mm 30mm"` might work for you (where you adjust the `30mm` to get the actual amount of offset that you want).

If your input pages are different heights, them perhaps pdfpages (and hence pdfjam) cannot help you.  It would not be hard to do this directly in LaTeX by using `\vfill`.  (But that's not much use if you are unfamiliar with LaTeX?)

**Comment by ahmedmohiduet** [comment]
Hadn't been familiar with that `-offset "0mm 30mm"` option. Since I have no `tex` file for that pdf file, LaTeX isn't an option for me. I think, I'm going to go with `offset` option. I have every page same height. Thank you @David.

**Comment by mgkurtz** [comment]
Such a feature seems sensible in general and could be done in `pdfpages` with not to much effort, but not here directly.
