### ISSUE TITLE
Request for info: Exclude pages counting from last

### ISSUE THREAD

**Issue by espinielli** [rrthomas/pdfjam#65]
I have the need to exclude the page before last from a PDF document where I have no prior knowledge of the total number of pages.
I see from `pdfpages` that you can refer last page as `last` but unfortunately no arithmetic support is provided, i.e. `last-1` will include all the pages in reverse order.

Any hints/suggestions are very welcome.

**Comment by DavidFirth** [comment]
My solution would be to run `pdfjam` three times:
1. with page range `last-1`, ie to reverse the pages
2. then with page range `1, 3-last` to omit the 2nd page of the reversed document
3. then with page range `last-1` to reverse the order again.
It's a bit clumsy, but should work?  (and easy enough to script if you need to do it repeatedly)

**Comment by espinielli** [comment]
Yeah, thought about it, but wanted to be sure there were no other more direct ways to do it.
Thanks a million for your time and suggestion!

**Comment by DavidFirth** [comment]
Slightly more direct, if you have `pdfinfo` available, would be to use that to get the page count and then run `pdfjam` just once.  (The arithmetic needed to subtract two from the page count would need to be done outside of `pdfjam`.)

**Comment by espinielli** [comment]
I scripted your suggestion and all works.
(The only issue is that I lose hyperlinking, i.e. from ToC to various chapter/sections or biblio. I guess reported in #44)
