### ISSUE TITLE
landscape and no-landscape mixed up

### ISSUE THREAD

**Issue by thw5858** [rrthomas/pdfjam#66]
in line 224 of pdfjam the values for paperwidth and paperheight should be exchanged. Instead of

    papersize="papersize={$paperheight$paperunit,$paperwidth$paperunitr}"

it should be 

    papersize="papersize={$paperwidth$paperunit,$paperheight$paperunit}"

Kind regards, Thomas

**Comment by rrthomas** [comment]
Apologies for this error; I have pushed the fix (thanks for supplying it!) and will now make a release.

**Comment by rrthomas** [comment]
I've now released 3.06 and uploaded it to CTAN.
