### ISSUE TITLE
"pdfjam --papersize" produces wrong pdf page size

### ISSUE THREAD

**Issue by milahu** [rrthomas/pdfjam#68]
in [my case](https://github.com/milahu/pdf-compress-vector-graphics), i have to scale the papersize argument by 1.0037491626 to get the expected papersize

```sh
# "pdfjam --papersize" produces wrong pdf page sizes
# does pdfjam add some border to the pdf page?
# TODO assert same pdf page size via pdfinfo
pdfjam_papersize_factor=1.0037491626
pdfjam_papersize_x=$(echo "scale=20; $page_pdf_width_pt * $pdfjam_papersize_factor" | bc)pt
pdfjam_papersize_y=$(echo "scale=20; $page_pdf_height_pt * $pdfjam_papersize_factor" | bc)pt
echo "using patched pdfjam papersize: $pdfjam_papersize_x,$pdfjam_papersize_y"

#pdfjam_args=(pdfjam --papersize "{$page_pdf_width,$page_pdf_height}" --scale $pdfjam_scale_x --offset "${pdfjam_offset_x}pt ${pdfjam_offset_y}pt" --outfile $jp2_pdf_path_scale_x $jp2_pdf_path_bak)
pdfjam_args=(pdfjam --papersize "{$pdfjam_papersize_x,$pdfjam_papersize_y}" --scale $pdfjam_scale_x --offset "${pdfjam_offset_x}pt ${pdfjam_offset_y}pt" --outfile $jp2_pdf_path_scale_x $jp2_pdf_path_bak)
```

example pages of my pdf: [page-146.pdf](https://github.com/rrthomas/pdfjam/files/12431197/page-146.pdf) (text only) and [page-061.input-vectors.pdf](https://github.com/milahu/pdf-rendering-chromium-versus-pdftoppm/blob/main/page-061.input-vectors.pdf) (vector graphics only)

in [my code](https://github.com/milahu/pdf-compress-vector-graphics), i process every pdf page:

- extract vector graphics with `gs -q -o $page_vectors_pdf_path -sDEVICE=pdfwrite -dFILTERIMAGE -dFILTERTEXT $page_pdf_path`
- render a png image with `pdftoppm -png $page_vectors_pdf_path $page_vectors_pdf_path.${resolution}dpi -f 1 -singlefile -r $resolution`
- detect objects in the png image with `convert -connected-components 4`

now i process every object:

- crop the object png image with `convert $page_png_path -crop $object_bbox +repage $object_png_path`
- compress to the object jp2 image with `convert $object_png_path -quality $jp2_quality $jp2_path`
- convert to the object pdf file with `img2pdf -o $jp2_pdf_path $jp2_path`

now the object pdf file has the wrong resolution (because i cant set resolution for img2pdf), and the wrong pagesize (because the image was cropped)

to fix this, i call `pdfjam --papersize "{$pdfjam_papersize_x,$pdfjam_papersize_y}" --scale $pdfjam_scale_x --offset "${pdfjam_offset_x}pt ${pdfjam_offset_y}pt" --outfile $jp2_pdf_path_scale_x $jp2_pdf_path_bak`

when i use the actual point sizes like `pdfjam --papersize "{419.528pt,637.795pt}"` then the result page size is too small by factor 1.0037491626

the workaround page size is 421.10087868725276pt x 640.1861971604669pt

note: im using [pdfselect](https://github.com/aur-archive/pdfselect) to select pages from my input pdf file.
also pdfselect adds a small error to the page size:

```
$ pdfinfo input.pdf | grep "^Page size:"
Page size:       419.528 x 637.795 pts

$ pdfinfo page-146.pdf | grep "^Page size:"
Page size:       419.527 x 637.793 pts
```

**Comment by rrthomas** [comment]
I have had this problem with pdfjam, and to be honest I gave up trying to use it for this sort of precise use. I use (and maintain) [pspdfutils](https://github.com/rrthomas/psutils) aka PSUtils, which in the current version 3.x also handles PDF natively. I suggest you take a look at it!

**Comment by lemniscati** [comment]
> when i use the actual point sizes like pdfjam --papersize "{419.528pt,637.795pt}" then the result page size is too small by factor 1.0037491626

Use `bp` instead of `pt` in TeX.

Please, note that 1in = 72.27pt = 72bp in TeX, and that `1bp` in TeX is 1pt of Adobe.
And the ratio bp/pt is 1.00375.

**Comment by rrthomas** [comment]
Thanks, @lemniscati, clearly a magic number to remember!

**Comment by milahu** [comment]
> Use `bp` instead of `pt` in TeX.

yes! thanks : )

so its surprising that pdfinfo's `pt` is different than pdfjam's `pt`
blame adobe: [Why does a TeX point differ from a Desktop Publishing point?](https://tex.stackexchange.com/questions/200934/why-does-a-tex-point-differ-from-a-desktop-publishing-point)

this affects (at least) pdfjam's `--papersize` and `--offset` options

can we add a paragraph to the help text? something like...

```
Note: Different PDF tools can have different definitions of the "pt" unit.
Latex has two point units:
pt: 72.27 pt = 1 inch (traditional pica point)
bp: 72.00 bp = 1 inch (big point)
```

**Comment by mgkurtz** [comment]
In bec16e8, I added support for `--papersize 419.528,637.795` which automatically adds `bp` as unit. Fixing this issue as good as it gets.

The `--papersize` option is currently the only option assuming dimensions which is handled directly by pdfjam. When and if I look into the various options simply passed on to pdfpages, I will also reflect on adding this feature to `--offset` and `--delta`.
