### ISSUE TITLE
Two issues with Cygwin hack

### ISSUE THREAD

**Issue by fhgwright** [rrthomas/pdfjam#69]
1. The non-Cygwin in Cygwin check added (in 6f2a7c8) uses "uname -o", which is a non-POSIX option.  I believe the default uname output is what's desired, so I don't know why the "-o" is present, other than to cause non-portability and spurious error messages.
2. It looks like the cacheing that was added to the check (in 45dff89) reversed the sense of the check.

Recommend:

1. Remove the "-o".
2. Unreverse the result sense.

**Comment by lemniscati** [comment]
Thank you for pointing out!
I made those commits.

1. I'll make a pull-request to avoid using  `uname` with `-o` option.
2. `__cache__using_non_cygwin_latex_from_cygwin` is stored as an exit status, and is expected to be used as
   ```
   return "${__cache__using_non_cygwin_latex_from_cygwin}"
   ```
   I agree that it is confusing, though...
   I have no idea, except replacing `__cache__` by `__exit_status__` or, so...

**Comment by rrthomas** [comment]
Thanks for the PR, @lemniscati.

**Comment by rrthomas** [comment]
Closing as fixed by #70.
