### ISSUE TITLE
Preserve original page size and orientation

### ISSUE THREAD

**Issue by RalfJung** [rrthomas/pdfjam#77]
One of my main usecases for pdfjam is to extract some pages from a PDF file. (I don't know any other utility that can do that.) Unfortunately, it seems like pdfjam will change the page size when doing that. What I expect to happen is that each page has exactly the same layout as it did in the original document, but instead the new document is entirely in portrait A4 no matter the page size and orientation of the original document. I can set `--landscape` but then if the original document was not A4 the page size is still wrong. Figuring out the exact page size is non-trivial.

Is there any way to take some pages from a PDF file without having to explicitly tell pdfjam what their size is?

**Comment by rrthomas** [comment]
`psselect` from [PSPDFUtils](https://pypi.org/project/pspdfutils/) would be my answer (disclaimer: I wrote and maintain PSPDFUtils, whereas I'm just the emergency interim maintainer of pdfjam!)

**Comment by RalfJung** [comment]
Thanks! I've found `pdftk` can also do it.
