### ISSUE TITLE
Option --landscape doesn't work unless --paper also specified

### ISSUE THREAD

**Issue by screwtop** [rrthomas/pdfjam#80]
I noticed recently after updating to pdfjam 3.10 that the `--landscape` option seemed to have no effect. In troubleshooting I found that specifying the paper size with `--paper a4paper` made it work again.

Unfortunately I'm not sure exactly what version I was running previously, but older PDF files it had generated held metadata referring to pdfTeX-1.40.25 and TeX Live 2023/Arch Linux.

Thanks!

**Comment by rrthomas** [comment]
Please try 3.11, as that fixes some issues in this area. Feel free to reopen if you still have a problem!
