### ISSUE TITLE
A `,` or `]` in options wracks `\includepdfmerge[…]`

### ISSUE THREAD

**Issue by mgkurtz** [rrthomas/pdfjam#84]
I just did
```sh
pdfjam --picturecommand '\put(20,20){Title}' file.pdf 10-13
```
resulting in
```tex
\includepdfmerge[picturecommand=\put(20,20){Title}]{/tmp/pdfjam-0UldqY/source-1.pdf,10-13}
```
which nastily thought, `20){Title}` where some esoteric key. Similar trouble happens for values containing `]`.

While special characters are troublesome in general, this case should be easy to fix by adding braces around all options, or at least around all options matching `[],]`.

I can look into this on my own and create a PR if wanted.

**Comment by rrthomas** [comment]
That would be great, @mgkurtz! I wonder if someone has done more general work on escaping parameters in this situation?

**Comment by mgkurtz** [comment]
> That would be great, @mgkurtz!

Nice. Seems, like I only need to add some tests and conditionally wrap the value in `{` and `}`.
```sh
if ...; then
  argValue = "{${2}}"
else
  argValue = "${2}"
fi
```
Then, use `$argValue` instead of `$value` for appending to `miscOptions` here:
https://github.com/rrthomas/pdfjam/blob/f0635e64a81b21802dc0fff01bdd2aa1f906fcb4/bin/pdfjam#L536-L541

> I wonder if someone has done more general work on escaping parameters in this situation?

I am unsure, what the general situation is. However, sanitizing in the sense of [replacing `$` by `\$` etc.](https://stackoverflow.com/questions/2627135/how-do-i-sanitize-latex-input) seems like a nice feature. So, if a new feature is wanted, one could add some option `--sanitize-args` to that end. But that would be another issue.

**Comment by rrthomas** [comment]
> I am unsure, what the general situation is. However, sanitizing in the sense of [replacing `$` by `\$` etc.](https://stackoverflow.com/questions/2627135/how-do-i-sanitize-latex-input) seems like a nice feature. So, if a new feature is wanted, one could add some option `--sanitize-args` to that end. But that would be another issue.

Sorry, I was unclear: I meant, I wonder whether there's anything written somewhere about escaping LaTeX arguments in general (not specific to pdfjam).

**Comment by mgkurtz** [comment]
> Sorry, I was unclear: I meant, I wonder whether there's anything written somewhere about escaping LaTeX arguments in general (not specific to pdfjam).

There is for sure in various programming languages. It’s just a few search and replace operations in general.

Anyway, I added some bash sanitizing to my PR. Somewhat unrelated, but seemed necessary either way.
